[project]
name = "captdevicecontrol"
version = "0.2.2"
authors = [
  { name="Christoph Schmidt", email="cschmidt.fs@gmail.com" },
]
description = "A UI for controlling the Analog Discovery Series"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    'matplotlib',
    'numpy',
    'pandas',
    'PySide6',
    'scipy',
    'rich',
    'pyqtgraph',
    'fswidgets@git+https://gitlab.tugraz.at/flexsensor-public/modules/fswidgets.git@develop',
    'confighandler@git+https://gitlab.tugraz.at/flexsensor-public/modules/confighandler.git@develop',
    'cmp@git+https://gitlab.tugraz.at/flexsensor-public/modules/cmp.git@develop'
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3.0",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://gitlab.tugraz.at/flexsensor-public/captdevicecontrol"